name: 'ci'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '^16.6.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

  # test:
  #   name: Test

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@master

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '^16.6.0'
  #         cache: 'yarn'

  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Run test
  #       run: yarn test:coverage --passWithNoTests

  #     - name: Upload coverage
  #       uses: codecov/codecov-action@v2
